### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by CWYuan08** [CCIVR/ccivr#2]
Hi @CCIVR , thank you very much sharing the tool, we would like to try CCIVR. but I cannot install it and the issue is:

WARNING: Built wheel for ccivr is invalid: Metadata 1.2 mandates PEP 440 version, but '0-2-0' is not
Failed to build ccivr
ERROR: Could not build wheels for ccivr, which is required to install pyproject.toml-based projects

Could you please help me on this?

Many thanks!
CW

**Comment by CCIVR** [comment]
Hello CW. Did you try pip3 instead, for installing CCIVR?

**Comment by CWYuan08** [comment]
Dear @CCIVR,

thank you for prompt reply!, with pip3, I am getting the same error:
WARNING: Built wheel for ccivr is invalid: Metadata 1.2 mandates PEP 440 version, but '0-2-0' is not
Failed to build ccivr
ERROR: Could not build wheels for ccivr, which is required to install pyproject.toml-based projects

not sure what this means. 

Best,
CW

**Comment by CCIVR** [comment]
Dear @CWYuan08 

Thank you for letting us know about this error. We have fixed some bugs. 
So, please try to install our software again as just the same as previously you did.
I believe that you can install our software successfully this time.
If there's something wrong again, please let us know.

Thanks again,
CCIVR team

**Comment by CWYuan08** [comment]
@CCIVR thank you very much for your help. 
I have managed to install ccivr, and run with my test file but got this error
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bin/ccivr", line 8, in <module>
    sys.exit(main())
  File "/lib/python3.7/site-packages/ccivr/ccivr.py", line 195, in main
    summary = write_summary(table,genes_total)
  File "/lib/python3.7/site-packages/ccivr/ccivr.py", line 131, in write_summary
    count_all = df['id'].nunique()
  File "/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'id'

I did have an id column in my input. could you please help me check this error?
Many thanks again.

Best,
CW
